const {Router} = require('express')
const {clienteRouters}= require('../routes/clienteRoutes')
const {categoriaRouters}= require('../routes/categoriaRoutes')
const {productoRouters}= require('../routes/productoRoutes')
const {pedidoRouters}= require('../routes/pedidoRoutes')
const {pedidoDetalleRouters}= require('../routes/DetallePedidoRoutes')
const {empleadoRouters} = require('../routes/EmpleadoRoutes')
const {estadoPedidoRouters} = require('../routes/EstadoPedidoRoutes')
const {facturaRouters} = require('../routes/FacturaRoutes')
const {historialEstadoRouters} = require('../routes/HistorialEstadoRoutes')
const {proyectoRouters} = require('../routes/ProyectoRoutes')
const {administradorRouters} = require('../routes/AdministradorRoutes')
const {imagenRouters} = require('../routes/ImagenRoutes')
const {logoRouters} = require('../routes/logoRoutes')

const router= Router()
router.use('/clientes',clienteRouters)
router.use('/categorias',categoriaRouters)
router.use('/productos',productoRouters)
router.use('/pedidos',pedidoRouters)
router.use('/detallePedido',pedidoDetalleRouters)
router.use('/empleado',empleadoRouters)
router.use('/estadoPedido',estadoPedidoRouters)
router.use('/factura',facturaRouters)
router.use('/historialEstado',historialEstadoRouters)
router.use('/proyecto',proyectoRouters)
router.use('/administrador',administradorRouters)
router.use('/imagen',imagenRouters)
router.use('/logo',logoRouters)

module.exports = router